
server:
    port: 8888
spring:
  cloud:
    config:
      server:
        git:
           uri: https://github.com/pruedaesntt/bootCamp-ConfigServer
#          uri: https://github.com/Milamaranth/microservices-cloud-config